spring:
  application:
    name: template-backend
  security:
    jwt:
      key: abcdefgijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/template
    username: root
    password: scp778899
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
    flow:
      period: 5
      limit: 100
      block: 30